#!/bin/sh

set -e -u -x

cp -r tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

for py in $(py3versions -s); do
    $py -m pytest -v 2>&1
done

python3 -c "import pastel; print(pastel.colorize('<info>This is a test green</info>'))" 2>&1
